module_name: zs
log_path: log/pipeline/serengeti_C02/ce/zs
class_names:
  - guineafowl
  - warthog
  - buffalo
  - giraffe
  - impala
  - hartebeest
  - elephant
  - zebra
  - gazellegrants
  - wildebeest
  - hyenaspotted
  - gazellethomsons
  - topi
common_config:
  model: bioclip
  train_data_config_path: config/data/serengeti_C02/train.json
  eval_data_config_path: config/data/serengeti_C02/test.json
  train_batch_size: 128
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  chop_head: false
pretrain_config:
  pretrain: false
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
