module_name: zs
log_path: log/pipeline/MAD_MAD01_new/ce/zs
class_names:
  - baboon
  - birdother
  - buffalo
  - civet
  - duikercommongrey
  - eland
  - elephant
  - giraffe
  - harecape
  - hippopotamus
  - honeybadger
  - hyenabrown
  - hyenaspotted
  - impala
  - jackalblackbacked
  - kudu
  - leopard
  - lionfemale
  - lionmale
  - mongoosebanded
  - mongooseunknown
  - monkeyvervet
  - porcupine
  - rhinocerosblack
  - rhinoceroswhite
  - springhare
  - tortoise
  - warthog
  - waterbuck
  - wilddog
  - wildebeestblue
  - zebraplains
  - zorilla
common_config:
  model: bioclip
  train_data_config_path: config/data/MAD_MAD01_new/train.json
  eval_data_config_path: config/data/MAD_MAD01_new/test.json
  train_batch_size: 128
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  chop_head: false
pretrain_config:
  pretrain: false
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
