module_name: accumulative-scratch
log_path: log/pipeline/serengeti_C02/cdt/accumulative-scratch
class_names:
  - guineafowl
  - warthog
  - buffalo
  - giraffe
  - impala
  - hartebeest
  - elephant
  - zebra
  - gazellegrants
  - wildebeest
  - hyenaspotted
  - gazellethomsons
  - topi
common_config:
  train_data_config_path: config/data/serengeti_C02/train.json
  eval_data_config_path: config/data/serengeti_C02/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025
pretrain_config:
  pretrain: false
ood_config:
  method: all
al_config:
  method: all
cl_config:
  method: accumulative-scratch
  epochs: 30
  loss_type: cdt
