module_name: zs
log_path: log/pipeline/APN_K024/ce/zs
class_names:
  - wildebeestblue
  - zebraburchells
  - steenbok
  - impala
  - giraffe
  - baboon
  - warthog
  - kudu
  - duikercommongrey
  - elephant
  - buffalo
common_config:
  model: bioclip
  train_data_config_path: config/data/APN/APN_K024/train.json
  eval_data_config_path: config/data/APN/APN_K024/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
pretrain_config:
  pretrain: false
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
