module_name: LWF
log_path: log/pipeline/ENO_B06/ce/LWF
class_names:
  - zebraplains
  - warthog
  - hyenaspotted
  - giraffe
  - eland
  - impala
  - buffalo
  - domesticanimal
  - gazellethomsons
  - baboon
  - wildebeestblue
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO_B06/train.json
  eval_data_config_path: config/data/ENO_B06/test.json
  train_batch_size: 128
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.00001
pretrain_config:
  pretrain: false
ood_config:
  method: all
al_config:
  method: all
cl_config:
  method: lwf
  buffer_size: 500
  epochs: 30
  loss_type: kd
