module_name: zs
log_path: log/pipeline/ENO_B06/ce/percentage-1
class_names:
  - zebraplains
  - warthog
  - hyenaspotted
  - giraffe
  - eland
  - impala
  - buffalo
  - domesticanimal
  - gazellethomsons
  - baboon
  - wildebeestblue
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO_B06/train.json
  eval_data_config_path: config/data/ENO_B06/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025 # 4 zeros
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025 # 5 zeros
pretrain_config:
  pretrain: true
  pretrain_data_config_path: config/data/ENO_B06/train-all.json
  epochs: 30
  loss_type: ce
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
