module_name: zs
log_path: log/pipeline/ENO_B06/ce/zs
class_names:
  - zebraplains
  - warthog
  - hyenaspotted
  - giraffe
  - eland
  - impala
  - buffalo
  - domesticanimal
  - gazellethomsons
  - baboon
  - wildebeestblue
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO/ENO_B06/train.json
  eval_data_config_path: config/data/ENO/ENO_B06/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
pretrain_config:
  pretrain: false
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
