module_name: LWF
log_path: log/pipeline/MAD_MAD05/ce/LWF
class_names:
  - aardvark
  - africanwildcat
  - baboon
  - birdother
  - buffalo
  - bushpig
  - caracal
  - elephant
  - giraffe
  - harecape
  - hyenabrown
  - hyenaspotted
  - impala
  - jackalblackbacked
  - kudu
  - leopard
  - lionfemale
  - mongoosebanded
  - mongooseunknown
  - porcupine
  - reedbuck
  - rhinocerosblack
  - rhinoceroswhite
  - springhare
  - steenbok
  - tortoise
  - warthog
  - wildebeestblue
  - zebraplains
common_config:
  model: bioclip
  train_data_config_path: config/data/MAD/MAD_MAD05/train.json
  eval_data_config_path: config/data/MAD/MAD_MAD05/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025
pretrain_config:
  pretrain: false
ood_config:
  method: all
al_config:
  method: all
cl_config:
  method: lwf
  buffer_size: 1000
  epochs: 30
  loss_type: kd
