module_name: zs
log_path: log/pipeline/MAD_MAD05_new/ce/zs
class_names:
  - aardvark
  - africanwildcat
  - baboon
  - birdother
  - buffalo
  - bushpig
  - caracal
  - elephant
  - giraffe
  - harecape
  - hyenabrown
  - hyenaspotted
  - impala
  - jackalblackbacked
  - kudu
  - leopard
  - lionfemale
  - mongoosebanded
  - mongooseunknown
  - porcupine
  - reedbuck
  - rhinocerosblack
  - rhinoceroswhite
  - springhare
  - steenbok
  - tortoise
  - warthog
  - wildebeestblue
  - zebraplains
common_config:
  model: bioclip2
  train_data_config_path: config/data/MAD/MAD_MAD05_new/train.json
  eval_data_config_path: config/data/MAD/MAD_MAD05_new/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
pretrain_config:
  pretrain: false
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
