module_name: regular
log_path: log/pipeline/APN_TB17_new/ce/regular
class_names:
  - aardvark
  - baboon
  - birdother
  - buffalo
  - civet
  - dikdik
  - duikercommongrey
  - elephant
  - giraffe
  - hippopotamus
  - hyenaspotted
  - impala
  - kudu
  - leopard
  - lioncub
  - lionfemale
  - lionmale
  - monkeyvervet
  - nyala
  - oribi
  - porcupine
  - reedbuck
  - rhinocerosunknown
  - steenbok
  - warthog
  - waterbuck
  - wildebeestblue
  - zebraburchells
common_config:
  model: bioclip
  train_data_config_path: config/data/APN_TB17_new/train.json
  eval_data_config_path: config/data/APN_TB17_new/test.json
  train_batch_size: 128
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.0001
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.00001
pretrain_config:
  pretrain: false
ood_config:
  method: all
al_config:
  method: all
cl_config:
  method: naive-ft
  epochs: 30
  loss_type: ce
