module_name: LWF
log_path: log/pipeline/ENO_C05_new/ce/lwf
class_names:
  - rhinocerosblack
  - baboon
  - harecape
  - impala
  - warthog
  - rhinoceroswhite
  - elephant
  - giraffe
  - zebraplains
  - hyenaspotted
  - wildebeestblue
  - buffalo
  - eland
  - domesticanimal
  - gazellethomsons
  - topi
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO_C05/train.json
  eval_data_config_path: config/data/ENO_C05/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025
pretrain_config:
  pretrain: false
ood_config:
  method: all
al_config:
  method: all
cl_config:
  method: lwf
  buffer_size: 1000
  epochs: 50
  loss_type: kd
