module_name: percentage-1
log_path: log/pipeline/ENO_C05_new/ce/percentage-1
class_names:
  - baboon
  - topi
  - plains zebra
  - thomson's gazelle
  - impala
  - african buffalo
  - warthog
  - domestic animal
  - blue wildebeest
  - giraffe
  - spotted hyena
  - eland
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO_C05_common_name/train.json
  eval_data_config_path: config/data/ENO_C05_common_name/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025
pretrain_config:
  pretrain: true
  pretrain_data_config_path: config/data/ENO_C05_common_name/train-all.json
  epochs: 30
  loss_type: ce
ood_config:
  method: none
al_config:
  method: none
cl_config:
  method: none
