module_name: oracle
log_path: log/pipeline/ENO_C05/oracle/ce
common_config:
  model: bioclip
  train_data_config_path: config/data/ENO_C05/30/train.json
  eval_data_config_path: config/data/ENO_C05/30/test.json
  train_batch_size: 32
  eval_batch_size: 512
  optimizer_name: AdamW
  optimizer_params:
    lr: 0.000025
    weight_decay: 0.0001
  chop_head: false
  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 30
    eta_min: 0.0000025
pretrain_config:
  pretrain: true
  pretrain_data_config_path: config/data/ENO_C05/30/train-all.json
  epochs: 1
  loss_type: ce
ood_config:
  method: none
al_config:
  method: cls_random
  percentage: 0.1
cl_config:
  method: none
